### ISSUE TITLE
RSSI feature missing

### ISSUE THREAD

**Issue by wbarnha** [wbarnha/gr-gmuground#14]
We need to add a RSSI on the GUI for users. We should probably readapt values from the link budget spreadsheet.

**Comment by wbarnha** [comment]
Apparently we can just integrate some indicator from [gr-guiextra](https://github.com/ghostop14/gr-guiextra), the LED Indicator is probably what we need.

**Comment by domnguyen19962000** [comment]
What value do you want to include in the GUI? Only SNR?

**Comment by wbarnha** [comment]
Whatever blocks are available, it seems that mapping SNRs is the best option for us.

**Comment by wbarnha** [comment]
![image](https://user-images.githubusercontent.com/25623043/77005649-885aef00-6937-11ea-9e6a-1e381d40a665.png)
Use this from the link budget spreadsheet as a reference.

**Comment by domnguyen19962000** [comment]
Sure. Which pages can I see that?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wbarnha** [comment]
More details are under "Modulation-Demodulation Method".

**Comment by wbarnha** [comment]
Take a look at `SNR_RSSI.grc` under `examples`, it seems the last issue for this is that the SNR from the SNR Estimation probe is not being mapped properly to a variable. Every time the SNR changes, I get the error: `gr::log 2020-03-18 17:36:35,472 :ERROR: Error with message conversion: pmt_cdr: wrong_type : 2.9065`

**Comment by wbarnha** [comment]
All set now, made a workaround in [my fork of gr-guiextra](https://github.com/wbarnha/gr-guiextra).
![Screenshot from 2020-03-20 16-32-40](https://user-images.githubusercontent.com/25623043/77204143-7e1c2a80-6ac8-11ea-9cb5-ba63a1067d41.png)
